server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://coderme.myds.me:33016/free_apps?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    #    url: jdbc:mysql://192.168.3.4:33016/free_apps?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/free_apps?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
